[package]
name = "rs-3d-polygon-to-triangles"
version = "0.1.0"
authors = ["Hugo VERJUS <hugo@verjus.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra =  {version = "0.18"}